services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    ports:
      - "9000:9000"
    depends_on:
      - db
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/var/www/html
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'ok';"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: ["/usr/local/bin/start.sh"]

volumes:
  postgres_data:
