version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: rehome_platform
      POSTGRES_USER: rehome_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rehome_network

  # Redis for Caching & Sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - rehome_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - backend_storage:/var/www/storage
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=rehome_platform
      - DB_USERNAME=rehome_user
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
      - redis
    networks:
      - rehome_network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:6001
    depends_on:
      - backend
    networks:
      - rehome_network

volumes:
  postgres_data:
  backend_storage:

networks:
  rehome_network:
    driver: bridge