name: Backend CI (Laravel)

on:
  push:
    branches: [ main, chore/rbac-flag-removal ]
    tags: [ 'v*' ]
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql, sqlite3, dom, fileinfo
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        working-directory: backend
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare environment
        working-directory: backend
        run: |
          cp .env.example .env || true
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          php artisan key:generate

      - name: Clear caches
        working-directory: backend
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      - name: Run unit tests
        working-directory: backend
        env:
          APP_ENV: testing
          CACHE_DRIVER: file
          SESSION_DRIVER: file
          QUEUE_CONNECTION: sync
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: vendor/bin/phpunit --testdox

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-logs
          path: |
            backend/storage/logs/*
            backend/bootstrap/cache/*
          if-no-files-found: ignore
