name: CI

  on:
    pull_request:
      branches: [main]

jobs:
  backend:
    name: Backend (Laravel)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_sqlite, sqlite3, dom, fileinfo
          coverage: none
      
      - name: Setup Composer cache
        uses: actions/cache@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run lint
        run: pnpm lint
      
      - name: Run typecheck
        run: pnpm typecheck
      
      - name: Run tests
        run: pnpm test