name: Frontend CI
on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
jobs:
  fe:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm run -s typecheck | tee ../public-artifacts/typecheck.log
      - name: Unit tests
        run: pnpm run -s test -- --run | tee ../public-artifacts/test.log
      - name: Build
        run: pnpm run -s build | tee ../public-artifacts/build.log
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fe-logs
          path: public-artifacts/**