name: Frontend CI
on:
  pull_request:
    paths: [ "frontend/**", ".github/workflows/frontend-ci.yml" ]
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ./frontend } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - run: corepack enable
      - run: corepack prepare pnpm@8.15.4 --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm run -s typecheck
      - run: pnpm run -s lint
      - run: pnpm run -s test -- --run --reporter=dot
      - run: NODE_OPTIONS="--max_old_space_size=4096" pnpm run -s build
      - run: NODE_OPTIONS="--max_old_space_size=4096" pnpm run -s storybook:ci
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: |
            frontend/.gatef_artifacts/**
            frontend/storybook-static/**
            frontend/coverage/**
          if-no-files-found: ignore