name: Frontend CI
on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm 8.15.4
        run: corepack prepare pnpm@8.15.4 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run -s typecheck

      - name: Lint
        run: pnpm run -s lint

      - name: Unit tests
        run: pnpm run -s test -- --run

      - name: Build
        run: pnpm run -s build

      - name: Storybook (CI)
        run: pnpm run -s storybook:ci

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: |
            frontend/.gatef_artifacts/**
            frontend/storybook-static/**
            frontend/coverage/**
          if-no-files-found: ignore