name: frontend-ci

on:
  push:
    paths: ["frontend/**", ".github/workflows/frontend-ci.yml"]
  pull_request:
    paths: ["frontend/**", ".github/workflows/frontend-ci.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm
      - name: Enable Corepack (pnpm 8.x)
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          pnpm -v
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint || pnpm exec eslint . --max-warnings=0
      - name: Typecheck
        run: pnpm run typecheck
      - name: Test
        run: pnpm run test -- --run --reporter=dot --test-timeout=30000
      - name: Storybook build (optional)
        if: ${{ always() }}
        run: NODE_OPTIONS="--max-old-space-size=4096" pnpm run storybook:ci
