name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths: ['frontend/**', '.github/workflows/frontend-ci.yml']
  pull_request:
    branches: [main, develop]
    paths: ['frontend/**', '.github/workflows/frontend-ci.yml']

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ui-changes: ${{ steps.filter.outputs.ui }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for UI changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ui:
              - 'frontend/src/**'
              - 'frontend/.storybook/**'
              - 'frontend/components/**'
              - 'frontend/public/**'
              - 'frontend/*.config.*'
              - 'frontend/package.json'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm 8.15.4
        run: corepack prepare pnpm@8.15.4 --activate

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Type check
        working-directory: frontend
        run: pnpm run -s typecheck

      - name: Run tests
        working-directory: frontend
        run: pnpm run -s test -- --run

  storybook:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.ui-changes == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm 8.15.4
        run: corepack prepare pnpm@8.15.4 --activate

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        working-directory: frontend
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: pnpm run storybook:ci || echo "Storybook build failed but continuing"